### PR TITLE
Fix concurent modification of timerlist

### LINKED ISSUE #24: E_CYCLE crashes with assertation on windows.
The problem is a corrupt vector iterator in void CTimerHandler::processTimedFBList(). The problem definitly occurs if only one E_CYCLE is used. This results in the runtime assert:
assert_cycle-FORTE

The following code fixes this:

```
void CTimerHandler::processTimedFBList() {
  bool fired;
  do {
    fired = false;
    // We keep a list of sorted entries (oldest at the beginning) so we only have to check the first entry in the list:
    auto it = mTimedFBList.begin();
    if (it != mTimedFBList.end() && it->mTimeOut <= mForteTime) {
      STimedFBListEntry entry = *it; // buffer entry
      it = mTimedFBList.erase(it);
      triggerTimedFB(entry);  // This adds the entry again if not a one shot.
      fired = true; // Check the next entry.
    }
  } while (fired);
}
```

### PR DESCRIPTION
**Pull request by azoitl**
Periodic entries in the timer list, wich are readded after triggering into the list resulted in a concurent modifcation. With this change the list is handled correctly and als copying of entries is reduced.

Fixes #24

### CODE REVIEW

File: src/arch/timerha.cpp [hunk 1]
```diff
@@ -82,13 +83,11 @@ void CTimerHandler::nextTick() {
...
 
 void CTimerHandler::processTimedFBList() {
-  for (auto it = mTimedFBList.begin(); it != mTimedFBList.end();) {
-    if (it->mTimeOut > mForteTime) {
-      break;  
-    }
-    STimedFBListEntry entry = *it; // buffer entry
-    it = mTimedFBList.erase(it);
-    triggerTimedFB(entry);
+  auto last = std::lower_bound(mTimedFBList.begin(), mTimedFBList.end(), mForteTime);
```
Comment (jwalt) [inline src/arch/timerha.cpp]: This is not equivalent. It leaves values that are equal to the target value in the list, whereas before equal values would be removed. The solution is to use `std::upper_bound`.

**Comment by kumajaya** [comment]
With std::upper_bound, I got "call to object of class type 'std::less<void>': no matching call operator found" error on VS Build Tools 2022

**Comment by azoitl** [comment]
> With std::upper_bound, I got "call to object of class type 'std::less': no matching call operator found" error on VS Build Tools 2022

can you say which operator is missing? would be important to fix this.

**Comment by kumajaya** [comment]
> > With std::upper_bound, I got "call to object of class type 'std::less': no matching call operator found" error on VS Build Tools 2022
> 
> can you say which operator is missing? would be important to fix this.

Reapplied this patch and rebuild but the error did not appear. I'll try a clean build and back to confirm.

**Comment by kumajaya** [comment]
> > With std::upper_bound, I got "call to object of class type 'std::less': no matching call operator found" error on VS Build Tools 2022
> 
> can you say which operator is missing? would be important to fix this.

Sorry, FALSE INFO. No errors at all.

**Comment by azoitl** [comment]
> > > With std::upper_bound, I got "call to object of class type 'std::less': no matching call operator found" error on VS Build Tools 2022
> > 
> > 
> > can you say which operator is missing? would be important to fix this.
> 
> Sorry, FALSE INFO. No errors at all.

No problem. First of all thx for testing. This is a critical patch. The more eyes the better.

File: src/arch/timerha.cpp (hunk 1 above)
Comment (azoitl) [reply src/arch/timerha.cpp]: Thx for pointing this out. Changed that.

**Review by jwalt — APPROVED** [review]

**Review by MartinMelikMerkumians — APPROVED** [review]
